---
- hosts: all
  remote_user: ansible
  become: yes
  connection: ssh

  vars:
   abc: git
   xyz: tree

  tasks:
    - name: installing git in my webservers
      action: dnf name='{{abc}}' state=present

    - name: installing tree package
      action: dnf name='{{xyz}}' state=present
...
